apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: manendrakmrdocker/chatapp-frontend:latest 
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"